### PR TITLE
Updating some W3C/NIST mappings, removal of non-fallback data

### PR DESCRIPTION
**Pull request by ronaldtse**
This PR fixes some W3C/NIST mappings and removes data that is not for fallback usage.

In the discussion with @strogonoff , we decided that this repo is currently serving as both the "fallback repo" and the "backup repo", which isn't the best role separation.

We should probably keep the "full backup" archive in a separate repo (and archive it!).

### CODE REVIEW

**Comment by strogonoff** [comment]
Ah, putting unmodified archive in an archived repo is probably most appropriate.

Looked at the diff. I’m only worried about removing the case-sensitive duplicates, since it would make it more difficult to incorporate upstream changes (if any occur), but aside from that no objections. And I see some missing misc mappings were added too, I’ve been meaning to review those issues…

**Comment by ronaldtse** [comment]
I will create a separate "backup" repo that is called the bibxml-data-backup that only contains the backup without any mappings.

**Comment by ronaldtse** [comment]
@strogonoff @kesara I have taken commit ad2c6f5a5 to create a new repository at https://github.com/ietf-ribose/bibxml-data-backup , which is meant to be the frozen backup and not intended to further change.

@kesara could you help migrate https://github.com/ietf-ribose/bibxml-data-backup to ietf-tools? There are no dependencies to change for it since it is frozen data. Thanks!

**Comment by ronaldtse** [comment]
From now on we will use this repository officially *not as a backup* but as a fallback repository.

**Comment by ronaldtse** [comment]
@kesara could we merge this PR since it:
* removes the unnecessary cruft (e.g. RDF files, temp files) from it
* adds additional mappings
?

Thanks!

**Comment by ronaldtse** [comment]
Thanks @kesara !

**Pull request merged**
